version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - '7001:5000'
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - db

  db:
    image: mysql:8.0.37
    restart: always
    environment:
      MYSQL_DATABASE: flask_back
      MYSQL_USER: mirbekov
      MYSQL_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: 1
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306